baseURL = "https://wananaiko.github.io/"
title = "PaperModX"
paginate = 5
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
env = "production"
description = "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
author = [ "Reorx" ]
mainSections = [ "docs", "posts" ]
disableAnchoredHeadings = true
images = [ "cover.png" ]
DateFormat = "2006-01-02"
useCustomAnalytics = true
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowWordCount = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
TocSide = "right"
EnableInstantClick = true
EnableImageZoom = true

[params.commentSystems.disqus]
shortname = "reorx"

[params.commentSystems.remark42]
url = "https://remark42.reorx.com"
site = "reorx.github.io"

[params.commentSystems.telegramWidget]
channel = "reorx_share"
accentColor = "9077e1"
limit = 20

  [params.defaultCommentSystems]
  remark42 = true

  [params.profileMode]
  enabled = false
  title = "PaperModX"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "/archives/"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "/tags/"

  [params.homeInfoParams]
  Title = "PaperModX"
  Content = """
Welcome to demo of hugo's theme PaperModX.

- **PaperModX** is a simple but fast and responsive theme with useful feature-set that enhances UX.

- PaperModX is based on theme [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

To get started, please head to the [Docs](docs).

To see examples of different contents, head to [examples tag](tags/example).
"""

  [[params.socialIcons]]
  name = "github-simple"
  url = "https://github.com/reorx/hugo-PaperModX"

  [[params.socialIcons]]
  name = "rss-simple"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Docs"
url = "/docs/"
weight = 1

[[languages.en.menu.main]]
name = "Newsletter"
url = "/newsletter/"
weight = 1

[[languages.en.menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 10

[[languages.en.menu.main]]
name = "@Author"
url = "https://reorx.com"

  [languages.en.menu.main.params]
  external = true

[languages.zh]
languageName = ":cn:"
languageAltTitle = "中文"
weight = 2
title = "PaperModX"

  [languages.zh.profileMode]
  enabled = true
  title = "PaperModX"
  subtitle = """
<p>Hugo 主题</p> ☄️ 快速 | ☁️ 流畅 | 📖 可读性 | 📱 响应式
"""

    [[languages.zh.profileMode.buttons]]
    name = "文档"
    url = "docs"

    [[languages.zh.profileMode.buttons]]
    name = "标签"
    url = "tags"

[[languages.zh.menu.main]]
name = "文档"
url = "docs"
weight = 1

[[languages.zh.menu.main]]
name = "标签"
url = "tags/"
weight = 4

[[languages.zh.menu.main]]
name = "归档"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "搜索"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "@作者"
url = "https://reorx.com"

  [languages.zh.menu.main.params]
  external = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
